### PR TITLE
Add support for running examples via cargo

### LINKED ISSUE #10: Add a way to run cargo examples
Currently, only binary targets seem to be supported.

### PR DESCRIPTION
**Pull request by killercup**
Fixes #10

### CODE REVIEW

**Comment by jonhoo** [comment]
I wonder -- should we make `bin`, `example`, [and `test`](https://www.reddit.com/r/rust/comments/b08oex/cargoflamegraph_generate_flame_graphs_directly/eidp5e3/) be subcommands instead of just flags? That way they could also have their own flags.

**Comment by killercup** [comment]
Hm, I thought the arguments were meant to be similar to cargo-run -- but that doesn't deal with tests or bechs so I'm not sure.

**Comment by jonhoo** [comment]
That's what I mean though. Maybe it should be:
```console
$ cargo flamegraph run --bin foobar
$ cargo flamegraph run --example foobar
$ cargo flamegraph test
$ cargo flamegraph bench
```

**Comment by robinst** [comment]
I was just looking if there was an open issue for running flamegraph for tests, being able to do `cargo flamegraph test` or `cargo flamegraph test mytestcase` would be nice!

**Comment by spacejam** [comment]
Thanks @killercup :D

**Comment by killercup** [comment]
I probably won't have time to change this PR for a while -- feel free to submit code based on it or merge as-is :)

**Comment by spacejam** [comment]
@jonhoo hmmm that does seem reasonable and consistent. I would like to default to the run behavior if no other command is entered, so that you can just type `cargo flamegraph` and have it generate what you need, but I think that's an approach that scales to others

**Comment by spacejam** [comment]
@killercup NP I fixed the conflict!

**Pull request merged**
